version: 2
jobs:
  build:
    environment:
      - GOPATH: /home/circleci/repo
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run:
          name: System information
          command: |
            echo "Golang $(go version)"
      - run: git submodule update --init
      - run: sudo apt-get install lua5.2
      - run: go get
      - run: go build
      - run: go test